#!/usr/bin/env bash
# Regenerate the flatbuffer schema artifacts used by `core-drill object` and
# the web viewer from the Icechunk .fbs files.
#
#   scripts/gen-schema.sh [path/to/icechunk/icechunk-format/flatbuffers]
#
# With no argument, regenerates from the .fbs copies already in schema/.
# Requires flatc (brew install flatbuffers) at the same major version as the
# `flatbuffers` crate in Cargo.lock.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA="$ROOT/schema"
FLATC_VERSION="$(flatc --version | awk '{print $3}')"

if [[ $# -ge 1 ]]; then
  cp "$1"/*.fbs "$SCHEMA/"
fi

cd "$SCHEMA"
# One binary schema per root type: the reflection verifier checks a buffer
# against the schema's root table.
for root in repo snapshot manifest transaction_log; do
  flatc --binary --schema --bfbs-builtins -o . "$root.fbs"
done

# The web viewer reads every type from one JSON export of the combined schema.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
curl -sfL "https://raw.githubusercontent.com/google/flatbuffers/v${FLATC_VERSION}/reflection/reflection.fbs" \
  -o "$TMP/reflection.fbs"
flatc --binary --schema --bfbs-builtins -o "$TMP" all.fbs
flatc --json --strict-json --raw-binary -o "$TMP" "$TMP/reflection.fbs" -- "$TMP/all.bfbs"
{
  echo "// Generated by scripts/gen-schema.sh from schema/*.fbs. Do not edit."
  printf 'window.ICECHUNK_SCHEMA = '
  cat "$TMP/all.json"
  echo ';'
} > "$ROOT/web/schema.js"

echo "Wrote schema/*.bfbs and web/schema.js (flatc $FLATC_VERSION)"
