#!/usr/bin/env bash
# Build web/vendor/zstd.js: the @bokuweb/zstd-wasm decoder as one classic
# script with its wasm inlined as base64, so the web viewer needs no network
# access and works from file://.
#
#   scripts/vendor-zstd.sh
#
# Requires node and npm. Downloads the pinned packages into a temporary
# directory; nothing is installed in the repository.
set -euo pipefail

ZSTD_WASM_VERSION="0.0.27"
ESBUILD_VERSION="0.28.2"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/web/vendor/zstd.js"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

cd "$TMP"
npm init -y >/dev/null
npm install --silent --no-audit --no-fund \
  "@bokuweb/zstd-wasm@$ZSTD_WASM_VERSION" "esbuild@$ESBUILD_VERSION"

# The package's web entry fetches zstd.wasm relative to import.meta.url.
# This entry passes the inlined bytes to the same emscripten module instead.
PKG="./node_modules/@bokuweb/zstd-wasm/dist/web"
cat > entry.js <<EOF
import { Module, waitInitialized } from '$PKG/module.js';
import wasm from '$PKG/zstd.wasm';
export { decompress } from '$PKG/simple/decompress.js';
export { createDCtx, decompressUsingDict } from '$PKG/simple/decompress_using_dict.js';

let ready = null;
export function init() {
  if (!ready) {
    Module.init(wasm);
    ready = waitInitialized();
  }
  return ready;
}
EOF

mkdir -p "$(dirname "$OUT")"
npx --no-install esbuild entry.js --bundle --format=iife --global-name=IcechunkZstd \
  --platform=browser --target=es2020 --loader:.wasm=binary --minify --legal-comments=none \
  --banner:js="// Generated by scripts/vendor-zstd.sh from @bokuweb/zstd-wasm@$ZSTD_WASM_VERSION (MIT; zstd itself is BSD-licensed). Do not edit.
// Defines the global IcechunkZstd: init(), decompress(), createDCtx(), decompressUsingDict()." \
  --outfile="$OUT" --log-level=warning

echo "Wrote web/vendor/zstd.js ($(wc -c < "$OUT" | tr -d ' ') bytes)"
