// Generated by scripts/gen-schema.sh from schema/*.fbs. Do not edit.
window.ICECHUNK_SCHEMA = {
  "objects": [
    {
      "name": "generated.ArrayManifest",
      "fields": [
        {
          "name": "extra",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 2,
          "offset": 8,
          "optional": true
        },
        {
          "name": "node_id",
          "type": {
            "base_type": "Obj",
            "index": 29,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "refs",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 8,
            "element_size": 4
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ArrayNodeData",
      "fields": [
        {
          "name": "dimension_names",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 11,
            "element_size": 4
          },
          "id": 1,
          "offset": 6,
          "optional": true
        },
        {
          "name": "manifests",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 21,
            "element_size": 4
          },
          "id": 2,
          "offset": 8,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "shape",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 12,
            "element_size": 16
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "shape_v2",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 13,
            "element_size": 4
          },
          "id": 3,
          "offset": 10,
          "optional": true
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ArrayUpdatedChunks",
      "fields": [
        {
          "name": "chunks",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 7,
            "element_size": 4
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "node_id",
          "type": {
            "base_type": "Obj",
            "index": 29,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.BranchCreatedUpdate",
      "fields": [
        {
          "name": "name",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.BranchDeletedUpdate",
      "fields": [
        {
          "name": "name",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "previous_snap_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.BranchResetUpdate",
      "fields": [
        {
          "name": "name",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "previous_snap_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ChunkIndexRange",
      "fields": [
        {
          "name": "from",
          "type": {
            "base_type": "UInt",
            "element_size": 1
          }
        },
        {
          "name": "to",
          "type": {
            "base_type": "UInt",
            "element_size": 1
          },
          "id": 1,
          "offset": 4
        }
      ],
      "is_struct": true,
      "minalign": 4,
      "bytesize": 8,
      "declaration_file": ""
    },
    {
      "name": "generated.ChunkIndices",
      "fields": [
        {
          "name": "coords",
          "type": {
            "base_type": "Vector",
            "element": "UInt",
            "element_size": 4
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ChunkRef",
      "fields": [
        {
          "name": "checksum_etag",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 6,
          "offset": 16,
          "optional": true
        },
        {
          "name": "checksum_last_modified",
          "type": {
            "base_type": "UInt",
            "element_size": 1
          },
          "id": 7,
          "offset": 18
        },
        {
          "name": "chunk_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "id": 4,
          "offset": 12,
          "optional": true
        },
        {
          "name": "compressed_location",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 8,
          "offset": 20,
          "optional": true
        },
        {
          "name": "extra",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 9,
          "offset": 22,
          "optional": true
        },
        {
          "name": "index",
          "type": {
            "base_type": "Vector",
            "element": "UInt",
            "element_size": 4
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "inline",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "optional": true
        },
        {
          "name": "length",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 3,
          "offset": 10
        },
        {
          "name": "location",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 5,
          "offset": 14,
          "optional": true
        },
        {
          "name": "offset",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 2,
          "offset": 8
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.CommitAmendedUpdate",
      "fields": [
        {
          "name": "branch",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "new_snap_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "id": 2,
          "offset": 8,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "previous_snap_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ConfigChangedUpdate",
      "fields": [

      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.DimensionName",
      "fields": [
        {
          "name": "name",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "optional": true
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.DimensionShape",
      "fields": [
        {
          "name": "array_length",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          }
        },
        {
          "name": "chunk_length",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 1,
          "offset": 8
        }
      ],
      "is_struct": true,
      "minalign": 8,
      "bytesize": 16,
      "declaration_file": ""
    },
    {
      "name": "generated.DimensionShapeV2",
      "fields": [
        {
          "name": "array_length",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "offset": 4
        },
        {
          "name": "num_chunks",
          "type": {
            "base_type": "UInt",
            "element_size": 1
          },
          "id": 1,
          "offset": 6
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ExpirationRanUpdate",
      "fields": [

      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.FeatureFlagChangedUpdate",
      "fields": [
        {
          "name": "id",
          "type": {
            "base_type": "UShort",
            "base_size": 2,
            "element_size": 1
          },
          "offset": 4
        },
        {
          "name": "is_set",
          "type": {
            "base_type": "Bool",
            "base_size": 1,
            "element_size": 1
          },
          "id": 2,
          "offset": 8
        },
        {
          "name": "new_value",
          "type": {
            "base_type": "Bool",
            "base_size": 1,
            "element_size": 1
          },
          "id": 1,
          "offset": 6
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.GCRanUpdate",
      "fields": [

      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.GroupNodeData",
      "fields": [

      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.Manifest",
      "fields": [
        {
          "name": "arrays",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 0,
            "element_size": 4
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "compression_algorithm",
          "type": {
            "base_type": "UByte",
            "base_size": 1,
            "element_size": 1
          },
          "id": 3,
          "offset": 10,
          "default_integer": 1
        },
        {
          "name": "extra",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 4,
          "offset": 12,
          "optional": true
        },
        {
          "name": "id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "location_dictionary",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 2,
          "offset": 8,
          "optional": true
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ManifestFileInfo",
      "fields": [
        {
          "name": "id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "padding": 4
        },
        {
          "name": "num_chunk_refs",
          "type": {
            "base_type": "UInt",
            "element_size": 1
          },
          "id": 2,
          "offset": 24,
          "padding": 4
        },
        {
          "name": "size_bytes",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 1,
          "offset": 16
        }
      ],
      "is_struct": true,
      "minalign": 8,
      "bytesize": 32,
      "declaration_file": ""
    },
    {
      "name": "generated.ManifestFileInfoV2",
      "fields": [
        {
          "name": "extra",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 3,
          "offset": 10,
          "optional": true
        },
        {
          "name": "id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "offset": 4,
          "optional": true
        },
        {
          "name": "num_chunk_refs",
          "type": {
            "base_type": "UInt",
            "element_size": 1
          },
          "id": 2,
          "offset": 8
        },
        {
          "name": "size_bytes",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 1,
          "offset": 6
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ManifestRef",
      "fields": [
        {
          "name": "extents",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 6,
            "element_size": 8
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "object_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.MetadataChangedUpdate",
      "fields": [

      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.MetadataItem",
      "fields": [
        {
          "name": "name",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "value",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.MoveOperation",
      "fields": [
        {
          "name": "from",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "optional": true
        },
        {
          "name": "node_id",
          "type": {
            "base_type": "Obj",
            "index": 29,
            "element_size": 1
          },
          "id": 2,
          "offset": 8,
          "optional": true
        },
        {
          "name": "node_type",
          "type": {
            "base_type": "UByte",
            "index": 1,
            "base_size": 1,
            "element_size": 1
          },
          "id": 3,
          "offset": 10
        },
        {
          "name": "to",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "optional": true
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.NewCommitUpdate",
      "fields": [
        {
          "name": "branch",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "new_snap_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.NewDetachedSnapshotUpdate",
      "fields": [
        {
          "name": "new_snap_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.NodeSnapshot",
      "fields": [
        {
          "name": "extra",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 5,
          "offset": 14,
          "optional": true
        },
        {
          "name": "id",
          "type": {
            "base_type": "Obj",
            "index": 29,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "node_data",
          "type": {
            "base_type": "Union",
            "index": 0,
            "element_size": 1
          },
          "id": 4,
          "offset": 12,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "node_data_type",
          "type": {
            "base_type": "UType",
            "index": 0,
            "base_size": 1,
            "element_size": 1
          },
          "id": 3,
          "offset": 10
        },
        {
          "name": "path",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "user_data",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 2,
          "offset": 8,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.ObjectId12",
      "fields": [
        {
          "name": "bytes",
          "type": {
            "base_type": "Array",
            "element": "UByte",
            "fixed_length": 12,
            "element_size": 1
          }
        }
      ],
      "is_struct": true,
      "minalign": 1,
      "bytesize": 12,
      "declaration_file": ""
    },
    {
      "name": "generated.ObjectId8",
      "fields": [
        {
          "name": "bytes",
          "type": {
            "base_type": "Array",
            "element": "UByte",
            "fixed_length": 8,
            "element_size": 1
          }
        }
      ],
      "is_struct": true,
      "minalign": 1,
      "bytesize": 8,
      "declaration_file": ""
    },
    {
      "name": "generated.Ref",
      "fields": [
        {
          "name": "name",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "snapshot_index",
          "type": {
            "base_type": "UInt",
            "element_size": 1
          },
          "id": 1,
          "offset": 6
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.Repo",
      "fields": [
        {
          "name": "branches",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 30,
            "element_size": 4
          },
          "id": 2,
          "offset": 8,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "config",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 9,
          "offset": 22,
          "attributes": [
            {
              "key": "flexbuffer",
              "value": "0"
            }
          ],
          "optional": true
        },
        {
          "name": "deleted_tags",
          "type": {
            "base_type": "Vector",
            "element": "String",
            "element_size": 4
          },
          "id": 3,
          "offset": 10,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "disabled_feature_flags",
          "type": {
            "base_type": "Vector",
            "element": "UShort",
            "element_size": 2
          },
          "id": 11,
          "offset": 26,
          "optional": true
        },
        {
          "name": "enabled_feature_flags",
          "type": {
            "base_type": "Vector",
            "element": "UShort",
            "element_size": 2
          },
          "id": 10,
          "offset": 24,
          "optional": true
        },
        {
          "name": "extra",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 12,
          "offset": 28,
          "optional": true
        },
        {
          "name": "latest_updates",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 41,
            "element_size": 4
          },
          "id": 7,
          "offset": 18,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "metadata",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 23,
            "element_size": 4
          },
          "id": 6,
          "offset": 16,
          "optional": true
        },
        {
          "name": "repo_before_updates",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 8,
          "offset": 20,
          "optional": true
        },
        {
          "name": "snapshots",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 37,
            "element_size": 4
          },
          "id": 4,
          "offset": 12,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "spec_version",
          "type": {
            "base_type": "UByte",
            "base_size": 1,
            "element_size": 1
          },
          "offset": 4
        },
        {
          "name": "status",
          "type": {
            "base_type": "Obj",
            "index": 34,
            "element_size": 1
          },
          "id": 5,
          "offset": 14,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "tags",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 30,
            "element_size": 4
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.RepoInitializedUpdate",
      "fields": [

      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.RepoMigratedUpdate",
      "fields": [
        {
          "name": "from_version",
          "type": {
            "base_type": "UByte",
            "base_size": 1,
            "element_size": 1
          },
          "offset": 4
        },
        {
          "name": "to_version",
          "type": {
            "base_type": "UByte",
            "base_size": 1,
            "element_size": 1
          },
          "id": 1,
          "offset": 6
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.RepoStatus",
      "fields": [
        {
          "name": "availability",
          "type": {
            "base_type": "UByte",
            "index": 2,
            "base_size": 1,
            "element_size": 1
          },
          "offset": 4
        },
        {
          "name": "limited_availability_reason",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 2,
          "offset": 8,
          "optional": true
        },
        {
          "name": "set_at",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 1,
          "offset": 6
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.RepoStatusChangedUpdate",
      "fields": [
        {
          "name": "status",
          "type": {
            "base_type": "Obj",
            "index": 34,
            "element_size": 1
          },
          "offset": 4,
          "optional": true
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.Snapshot",
      "fields": [
        {
          "name": "extra",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 8,
          "offset": 20,
          "optional": true
        },
        {
          "name": "flushed_at",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 3,
          "offset": 10
        },
        {
          "name": "id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "manifest_files",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 19,
            "element_size": 32
          },
          "id": 6,
          "offset": 16,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "manifest_files_v2",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 20,
            "element_size": 4
          },
          "id": 7,
          "offset": 18,
          "optional": true
        },
        {
          "name": "message",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 4,
          "offset": 12,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "metadata",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 23,
            "element_size": 4
          },
          "id": 5,
          "offset": 14,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "nodes",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 27,
            "element_size": 4
          },
          "id": 2,
          "offset": 8,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "parent_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "optional": true
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.SnapshotInfo",
      "fields": [
        {
          "name": "flushed_at",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 2,
          "offset": 8
        },
        {
          "name": "id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "message",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 3,
          "offset": 10,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "metadata",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 23,
            "element_size": 4
          },
          "id": 4,
          "offset": 12,
          "optional": true
        },
        {
          "name": "parent_offset",
          "type": {
            "base_type": "Int",
            "element_size": 1
          },
          "id": 1,
          "offset": 6
        },
        {
          "name": "pruned_ancestor_tx_logs",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 28,
            "element_size": 12
          },
          "id": 5,
          "offset": 14,
          "optional": true
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.TagCreatedUpdate",
      "fields": [
        {
          "name": "name",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.TagDeletedUpdate",
      "fields": [
        {
          "name": "name",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "previous_snap_id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.TransactionLog",
      "fields": [
        {
          "name": "deleted_arrays",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 29,
            "element_size": 8
          },
          "id": 4,
          "offset": 12,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "deleted_groups",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 29,
            "element_size": 8
          },
          "id": 3,
          "offset": 10,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "extra",
          "type": {
            "base_type": "Vector",
            "element": "UByte",
            "element_size": 1
          },
          "id": 9,
          "offset": 22,
          "optional": true
        },
        {
          "name": "id",
          "type": {
            "base_type": "Obj",
            "index": 28,
            "element_size": 1
          },
          "offset": 4,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "moved_nodes",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 24,
            "element_size": 4
          },
          "id": 8,
          "offset": 20,
          "optional": true
        },
        {
          "name": "new_arrays",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 29,
            "element_size": 8
          },
          "id": 2,
          "offset": 8,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "new_groups",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 29,
            "element_size": 8
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "updated_arrays",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 29,
            "element_size": 8
          },
          "id": 5,
          "offset": 14,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "updated_chunks",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 2,
            "element_size": 4
          },
          "id": 7,
          "offset": 18,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "updated_groups",
          "type": {
            "base_type": "Vector",
            "element": "Obj",
            "index": 29,
            "element_size": 8
          },
          "id": 6,
          "offset": 16,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    },
    {
      "name": "generated.Update",
      "fields": [
        {
          "name": "backup_path",
          "type": {
            "base_type": "String",
            "element_size": 1
          },
          "id": 3,
          "offset": 10,
          "optional": true
        },
        {
          "name": "update_type",
          "type": {
            "base_type": "Union",
            "index": 3,
            "element_size": 1
          },
          "id": 1,
          "offset": 6,
          "required": true,
          "attributes": [
            {
              "key": "required",
              "value": "0"
            }
          ]
        },
        {
          "name": "update_type_type",
          "type": {
            "base_type": "UType",
            "index": 3,
            "base_size": 1,
            "element_size": 1
          },
          "offset": 4
        },
        {
          "name": "updated_at",
          "type": {
            "base_type": "ULong",
            "base_size": 8,
            "element_size": 1
          },
          "id": 2,
          "offset": 8
        }
      ],
      "minalign": 1,
      "declaration_file": ""
    }
  ],
  "enums": [
    {
      "name": "generated.NodeData",
      "values": [
        {
          "name": "NONE",
          "value": 0,
          "union_type": {
            "base_size": 1,
            "element_size": 1
          }
        },
        {
          "name": "Array",
          "value": 1,
          "union_type": {
            "base_type": "Obj",
            "index": 1,
            "element_size": 1
          }
        },
        {
          "name": "Group",
          "value": 2,
          "union_type": {
            "base_type": "Obj",
            "index": 17,
            "element_size": 1
          }
        }
      ],
      "is_union": true,
      "underlying_type": {
        "base_type": "UType",
        "index": 0,
        "base_size": 1,
        "element_size": 1
      },
      "declaration_file": ""
    },
    {
      "name": "generated.NodeType",
      "values": [
        {
          "name": "Group",
          "value": 0,
          "union_type": {
            "base_size": 1,
            "element_size": 1
          }
        },
        {
          "name": "Array",
          "value": 1,
          "union_type": {
            "base_size": 1,
            "element_size": 1
          }
        }
      ],
      "underlying_type": {
        "base_type": "UByte",
        "index": 1,
        "base_size": 1,
        "element_size": 1
      },
      "declaration_file": ""
    },
    {
      "name": "generated.RepoAvailability",
      "values": [
        {
          "name": "Online",
          "value": 0,
          "union_type": {
            "base_size": 1,
            "element_size": 1
          }
        },
        {
          "name": "ReadOnly",
          "value": 1,
          "union_type": {
            "base_size": 1,
            "element_size": 1
          }
        },
        {
          "name": "Offline",
          "value": 2,
          "union_type": {
            "base_size": 1,
            "element_size": 1
          }
        }
      ],
      "underlying_type": {
        "base_type": "UByte",
        "index": 2,
        "base_size": 1,
        "element_size": 1
      },
      "declaration_file": ""
    },
    {
      "name": "generated.UpdateType",
      "values": [
        {
          "name": "NONE",
          "value": 0,
          "union_type": {
            "base_size": 1,
            "element_size": 1
          }
        },
        {
          "name": "RepoInitializedUpdate",
          "value": 1,
          "union_type": {
            "base_type": "Obj",
            "index": 32,
            "element_size": 1
          }
        },
        {
          "name": "RepoMigratedUpdate",
          "value": 2,
          "union_type": {
            "base_type": "Obj",
            "index": 33,
            "element_size": 1
          }
        },
        {
          "name": "ConfigChangedUpdate",
          "value": 3,
          "union_type": {
            "base_type": "Obj",
            "index": 10,
            "element_size": 1
          }
        },
        {
          "name": "MetadataChangedUpdate",
          "value": 4,
          "union_type": {
            "base_type": "Obj",
            "index": 22,
            "element_size": 1
          }
        },
        {
          "name": "TagCreatedUpdate",
          "value": 5,
          "union_type": {
            "base_type": "Obj",
            "index": 38,
            "element_size": 1
          }
        },
        {
          "name": "TagDeletedUpdate",
          "value": 6,
          "union_type": {
            "base_type": "Obj",
            "index": 39,
            "element_size": 1
          }
        },
        {
          "name": "BranchCreatedUpdate",
          "value": 7,
          "union_type": {
            "base_type": "Obj",
            "index": 3,
            "element_size": 1
          }
        },
        {
          "name": "BranchDeletedUpdate",
          "value": 8,
          "union_type": {
            "base_type": "Obj",
            "index": 4,
            "element_size": 1
          }
        },
        {
          "name": "BranchResetUpdate",
          "value": 9,
          "union_type": {
            "base_type": "Obj",
            "index": 5,
            "element_size": 1
          }
        },
        {
          "name": "NewCommitUpdate",
          "value": 10,
          "union_type": {
            "base_type": "Obj",
            "index": 25,
            "element_size": 1
          }
        },
        {
          "name": "CommitAmendedUpdate",
          "value": 11,
          "union_type": {
            "base_type": "Obj",
            "index": 9,
            "element_size": 1
          }
        },
        {
          "name": "NewDetachedSnapshotUpdate",
          "value": 12,
          "union_type": {
            "base_type": "Obj",
            "index": 26,
            "element_size": 1
          }
        },
        {
          "name": "GCRanUpdate",
          "value": 13,
          "union_type": {
            "base_type": "Obj",
            "index": 16,
            "element_size": 1
          }
        },
        {
          "name": "ExpirationRanUpdate",
          "value": 14,
          "union_type": {
            "base_type": "Obj",
            "index": 14,
            "element_size": 1
          }
        },
        {
          "name": "FeatureFlagChangedUpdate",
          "value": 15,
          "union_type": {
            "base_type": "Obj",
            "index": 15,
            "element_size": 1
          }
        },
        {
          "name": "RepoStatusChangedUpdate",
          "value": 16,
          "union_type": {
            "base_type": "Obj",
            "index": 35,
            "element_size": 1
          }
        }
      ],
      "is_union": true,
      "underlying_type": {
        "base_type": "UType",
        "index": 3,
        "base_size": 1,
        "element_size": 1
      },
      "declaration_file": ""
    }
  ],
  "file_ident": "",
  "file_ext": "",
  "services": [

  ],
  "advanced_features": "AdvancedArrayFeatures"
}
;
